[project]
name = "uv-myproject"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=1.24.4",
    "torch",
    "torchvision",
]

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cu118"
default = true
